name: "Test the pre-commit shell scripts in zsh"
description: "Only works when ran on macos"

runs:
  using: "composite"
  steps:
    - name: Install python and set up Poetry
      uses: bakdata/ci-templates/actions/python-setup-poetry@v1.5.2
      with:
        poetry-version: "1.3.2"
        python-version: "3.10"

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run pre-commit-hooks
      shell: zsh {0}
      run: |
        poetry run mypy pre-commit run --all-files --show-diff-on-failure
        poetry run gen-docs pre-commit run --all-files --show-diff-on-failure
