name: "Test the pre-commit shell scripts in zsh"
description: ""

runs:
  using: "composite"
  steps:
    - name: Install zsh
      run: sudo apt-get update; sudo apt-get install zsh
      shell: bash

    - name: Run pre-commit-hooks
      shell: /usr/bin/zsh{0}
      run: |
        poetry run pre-commit run mypy --all-files --show-diff-on-failure
        poetry run pre-commit run gen-docs --all-files --show-diff-on-failure
