name: "Test the pre-commit shell scripts in zsh"
description: ""

runs:
  using: "composite"
  steps:
    - name: Install python and set up Poetry
      uses: bakdata/ci-templates/actions/python-setup-poetry@v1.5.2
      with:
        poetry-version: "1.3.2"
        python-version: "3.10"
      
    - name: Install zsh
      run: sudo apt-get update; sudo apt-get install zsh
      shell: bash

    - name: Install dependencies
      shell: /usr/bin/zsh{0}
      run: poetry install --no-interaction

    - name: Run pre-commit-hooks
      shell: /usr/bin/zsh{0}
      run: |
        poetry run pre-commit run mypy --all-files --show-diff-on-failure
        poetry run pre-commit run gen-docs --all-files --show-diff-on-failure
