# Holds configuration to use as values for the streams bootstrap producer Helm
# chart.
# More documentation on ProducersApp:
# https://github.com/bakdata/streams-bootstrap
- type: producer-app
  name: producer-app # required
