name: "KPOps runner"
description: "Run KPOps command with the given params"

inputs:
  command:
    description: "The KPOps command to run"
    required: true
  pipeline:
    description: "Pipeline to run"
    required: true
  working-directory:
    description: "The root directory containing the config.yaml, pipelines folder and defaults"
    default: "."
  pipeline-base-dir:
    description: "Directory where relative pipeline variables are initialized from"
    default: "."
  defaults:
    description: "Defaults folder path"
    default: "defaults"
  config:
    description: "config.yaml file path"
    default: "config.yaml"
  components:
    description: "Components package path"
    required: false
  kpops-version:
    description: "KPOps version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install KPOps
      shell: bash
      run: |
        echo "::group::pip install kpops package"
        pip install kpops==${{ inputs.kpops-version }}
        echo "::endgroup::"

    - name: ${{ inputs.command }} ${{ inputs.pipeline }} pipeline
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: kpops ${{ inputs.command }} ${{ inputs.pipeline }} ${{ inputs.components }} --defaults ${{ inputs.defaults }} --config ${{ inputs.config }} --pipeline-base-dir ${{ inputs.pipeline-base-dir }}
