name: "Generate all files related to documentation"

description: "Generates all files related to documentation."

inputs:
  username:
    description: "GitHub username"
    required: true
  email:
    description: "GitHub email"
    required: true
  token:
    description: "GitHub Token (must be a PAT for repository dispatch)"
    required: true
  python-version:
    description: "Poetry version"
    required: true
  poetry-version:
    description: "Poetry version"
    required: true
  just-version:
    description: "Just version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install python and set up Poetry
      uses: bakdata/ci-templates/actions/python-setup-poetry@v1.5.3
      with:
        poetry-version: ${{ inputs.poetry-version }}
        python-version: ${{ inputs.python-version }}

    - name: Install optional dependencies
      shell: bash
      run: poetry install --with docs

    - name: Install just
      uses: extractions/setup-just@v1
      with:
        just-version: ${{ inputs.just-version }}

    - name: Generate CLI Usage page
      shell: bash
      run: |
        # Generate page with typer-cli
        poetry run just generate-doc-cli-usage

    - name: Commit and push changes
      uses: bakdata/ci-templates/actions/commit-and-push@main
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        commit-message: "docs(cli): Autogenerate CLI Usage page"
        add-untracked: "false"
        github-username: ${{ inputs.username }}
        github-email: ${{ inputs.email }}
        github-token: ${{ inputs.token }}
