"""Copies ``CONTROBUTING.md`` from root to the docs."""
import shutil
from pathlib import Path
from tempfile import TemporaryFile

KPOPS_ROOT = Path(__file__).parents[2].resolve()
SOURCE = KPOPS_ROOT / "CONTRIBUTING.md"
DEST = KPOPS_ROOT / "docs/docs/developer/contributing.md"
HEADER = f"<!-- This file is autogenerated by {Path(__file__).relative_to(KPOPS_ROOT)}. -->\n\n".encode()

# Copy `CONTRIBUTING.md` into the equivalent file in the docs,
# adding a comment at the top which notes that the file is generated
with (
    TemporaryFile() as file_header,
    DEST.open("w+b") as file_dest,
    SOURCE.open("rb") as file_source,
):
    file_header.write(HEADER)
    file_header.seek(0)
    shutil.copyfileobj(file_header, file_dest)
    shutil.copyfileobj(file_source, file_dest)
