import inspect
import shutil
from pathlib import Path
from tempfile import TemporaryFile

from hooks import ROOT


def copy_file(
    source: Path,
    dest: Path,
    *,
    add_header: bool | None = None,
    header: str | None = None,
) -> None:
    r"""Copy file from 1 location to another, optionally add a header.

    :param source: Path to file to be copied
    :param dest: Path to new file
    :param add_header: Whether to add header
    :param header: Will be placed at the top of the file, defaults to
        ``f"<!-- This file is autogenerated by {Path(__file__).relative_to(ROOT)}. -->\n\n"``
        NOTE: The default header will only contain correct information if the caller of
        this function is the one which should be referenced in the header
    """
    with dest.open("w+b") as file_dest, source.open("rb") as file_source:
        if not add_header:
            shutil.copyfileobj(file_source, file_dest)
            return
        if header is None:
            header_encoded = f"<!-- This file is autogenerated by {Path(inspect.stack()[1].filename ).relative_to(ROOT)}. -->\n\n".encode()
        else:
            header_encoded = header.encode()
        with TemporaryFile() as file_header:
            file_header.write(header_encoded)
            file_header.seek(0)
            shutil.copyfileobj(file_header, file_dest)
            shutil.copyfileobj(file_source, file_dest)
