  # Helm repository configuration (optional)
  # If not set the helm repo add will not be called. Useful when using local Helm charts
  repoConfig:
    repositoryName: my-repo # required
    url: https://bakdata.github.io/ # required
    repoAuthFlags:
      username: user
      password: pass
      ca_file: /home/user/path/to/ca-file
      insecure_skip_tls_verify: false
