# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import GenericRepr, Snapshot


snapshots = Snapshot()

snapshots['TestManifest.test_python_api resource 0'] = [
    GenericRepr("{'apiVersion': 'batch/v1', 'kind': 'Job', 'metadata': {'name': 'resources-custom-config-app1', 'labels': {'app': 'resources-custom-config-app1', 'chart': 'producer-app-2.9.0', 'release': 'resources-custom-config-app1'}}, 'spec': {'template': {'metadata': {'labels': {'app': 'resources-custom-config-app1', 'release': 'resources-custom-config-app1'}}, 'spec': {'restartPolicy': 'OnFailure', 'affinity': None, 'containers': [{'name': 'resources-custom-config-app1', 'image': 'producerApp:latest', 'imagePullPolicy': 'Always', 'resources': {'limits': {'cpu': '500m', 'memory': '2G'}, 'requests': {'cpu': '200m', 'memory': '2G'}}, 'env': [{'name': 'ENV_PREFIX', 'value': 'APP_'}, {'name': 'APP_BROKERS', 'value': 'http://k8kafka-cp-kafka-headless.kpops.svc.cluster.local:9092'}, {'name': 'APP_SCHEMA_REGISTRY_URL', 'value': 'http://localhost:8081/'}, {'name': 'APP_DEBUG', 'value': 'false'}, {'name': 'APP_OUTPUT_TOPIC', 'value': 'resources-custom-config-app1'}, {'name': 'JAVA_TOOL_OPTIONS', 'value': '-XX:MaxRAMPercentage=75.0 '}]}]}}, 'backoffLimit': 6}}")
]

snapshots['TestManifest.test_python_api resource 1'] = [
    GenericRepr('{\'apiVersion\': \'v1\', \'kind\': \'ConfigMap\', \'metadata\': {\'name\': \'resources-custom-config-app2-jmx-configmap\', \'labels\': {\'app\': \'resources-custom-config-app2\', \'chart\': \'streams-app-2.9.0\', \'release\': \'resources-custom-config-app2\', \'heritage\': \'Helm\'}}, \'data\': {\'jmx-kafka-streams-app-prometheus.yml\': \'jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi\\nlowercaseOutputName: true\\nlowercaseOutputLabelNames: true\\nssl: false\\nrules:\\n  - pattern: ".*"\\n\'}}'),
    GenericRepr("{'apiVersion': 'apps/v1', 'kind': 'Deployment', 'metadata': {'name': 'resources-custom-config-app2', 'labels': {'app': 'resources-custom-config-app2', 'chart': 'streams-app-2.9.0', 'release': 'resources-custom-config-app2', 'pipeline': 'resources-custom-config'}}, 'spec': {'replicas': 1, 'selector': {'matchLabels': {'app': 'resources-custom-config-app2', 'release': 'resources-custom-config-app2'}}, 'template': {'metadata': {'annotations': {'prometheus.io/scrape': 'true', 'prometheus.io/port': '5556'}, 'labels': {'app': 'resources-custom-config-app2', 'release': 'resources-custom-config-app2', 'pipeline': 'resources-custom-config'}}, 'spec': {'affinity': {'podAntiAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 1, 'podAffinityTerm': {'topologyKey': 'kubernetes.io/hostname', 'labelSelector': {'matchExpressions': [{'key': 'app', 'operator': 'In', 'values': ['resources-custom-config-app2']}]}}}]}}, 'containers': [{'name': 'resources-custom-config-app2', 'image': 'some-image:latest', 'imagePullPolicy': 'Always', 'resources': {'limits': {'cpu': '500m', 'memory': '2G'}, 'requests': {'cpu': '200m', 'memory': '300Mi'}}, 'env': [{'name': 'ENV_PREFIX', 'value': 'APP_'}, {'name': 'KAFKA_JMX_PORT', 'value': '5555'}, {'name': 'APP_VOLATILE_GROUP_INSTANCE_ID', 'value': 'true'}, {'name': 'APP_BROKERS', 'value': 'http://k8kafka-cp-kafka-headless.kpops.svc.cluster.local:9092'}, {'name': 'APP_SCHEMA_REGISTRY_URL', 'value': 'http://localhost:8081/'}, {'name': 'APP_DEBUG', 'value': 'false'}, {'name': 'APP_INPUT_TOPICS', 'value': 'resources-custom-config-app1'}, {'name': 'APP_OUTPUT_TOPIC', 'value': 'resources-custom-config-app2'}, {'name': 'APP_ERROR_TOPIC', 'value': 'resources-custom-config-app2-error'}, {'name': 'JAVA_TOOL_OPTIONS', 'value': '-Dcom.sun.management.jmxremote.port=5555 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -XX:MaxRAMPercentage=75.0 '}], 'ports': [{'containerPort': 5555, 'name': 'jmx'}]}, {'name': 'prometheus-jmx-exporter', 'image': 'solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143', 'command': ['java', '-XX:+UnlockExperimentalVMOptions', '-XX:+UseCGroupMemoryLimitForHeap', '-XX:MaxRAMFraction=1', '-XshowSettings:vm', '-jar', 'jmx_prometheus_httpserver.jar', '5556', '/etc/jmx-streams-app/jmx-kafka-streams-app-prometheus.yml'], 'ports': [{'containerPort': 5556}], 'resources': {'limits': {'cpu': '300m', 'memory': '2G'}, 'requests': {'cpu': '100m', 'memory': '500Mi'}}, 'volumeMounts': [{'name': 'jmx-config', 'mountPath': '/etc/jmx-streams-app'}]}], 'volumes': [{'name': 'jmx-config', 'configMap': {'name': 'resources-custom-config-app2-jmx-configmap'}}]}}}}")
]
