name: "Update documentation in gh-pages"
description: |
  Compile markdown documents to html and deploy to docs branch. If a semver version is given, this action strips the patch.
  It then pushes the <major>.<minor> as the latest alias to the documentation branch with mike.

inputs:
  username:
    description: "GitHub username"
    required: true
  email:
    description: "GitHub email"
    required: true
  token:
    description: "GitHub Token (must be a PAT for repository dispatch)"
    required: true
  version:
    description: "Version name to be deployed by mike"
    required: true 
  release:
    description: "Determines if the set version is a stable and latest version, otherwise it is a dev version. (Default false)"
    default: 'false'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Python and set up Poetry
      uses: bakdata/ci-templates/actions/python-setup-poetry@v1.5.2
      with:
        poetry-version: "1.5.1"
        python-version: "3.10"

    - name: Install docs dependencies
      shell: bash
      run: |
        poetry install --with docs

    - name: Update ${{ github.head_ref }} branch
      shell: bash
      run: |
        git config --local user.name  ${{ inputs.username }}
        git config --local user.email ${{ inputs.email }}
        git config --local user.password ${{ inputs.token }}

        git pull 

    - name: Deploy ${{ inputs.version }} version of the documentation with mike
      shell: bash
      if: ${{ inputs.release == 'false' }}
      run: |
        poetry run mike deploy ${{ inputs.version }} --push --rebase --config-file ./docs/mkdocs.yml

    - name: Deploy ${{ inputs.version }} version (latest) of the documentation with mike
      shell: bash
      if: ${{ inputs.release == 'true' }}
      run: |
        sem_version=${{ inputs.version }}
        major_minor_version=${sem_version%.*}
        poetry run mike deploy "${{ inputs.version }}" latest --update-aliases --push --rebase --config-file ./docs/mkdocs.yml
