name: Lint GitHub CI

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - actions/**

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Lint actions and workflows
        uses: bakdata/ci-templates/actions/action-lint@v1.14.0
        with:
          action-lint-version: "v1.7.6"
