name: CI

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          # - windows-2022  # FIXME
        python-version: [ "3.10", "3.11" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Python and set up Poetry
        uses: bakdata/ci-templates/actions/python-setup-poetry@v1.5.3
        with:
          poetry-version: "1.5.1"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint (flake8)
        run: poetry run pre-commit run flake8 --all-files --show-diff-on-failure

      - name: Order of imports (isort)
        run: poetry run pre-commit run isort --all-files --show-diff-on-failure

      - name: Formatting (black)
        run: poetry run pre-commit run black --all-files --show-diff-on-failure

      - name: Typing (pyright)
        run: poetry run pre-commit run pyright --all-files

      - name: Generate schema (kpops schema)
        run: poetry run pre-commit run gen-schema --all-files --show-diff-on-failure

      - name: Generate docs (typer-cli)
        run: poetry run pre-commit run gen-docs --all-files --show-diff-on-failure

      # TODO: enable when PEP 604 incompatibilty is in typer is resolved https://github.com/tiangolo/typer/issues/348
      # See https://github.com/tiangolo/typer/pull/522
      # - name: Syntax (pyupgrade)
      #   run: poetry run pre-commit run --hook-stage manual pyupgrade --all-files

      - name: Test
        run: poetry run pytest tests

      - name: Install docs dependencies
        run: poetry install --with docs

      - name: Test docs build (mkdocs)
        run: poetry run mkdocs build -f docs/mkdocs.yml

  publish:
    name: Publish
    needs: [test]
    uses: ./.github/workflows/publish-test-pypi.yaml
    secrets:
      test-pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}
