name: CI

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install python and set up Poetry
        uses: bakdata/ci-templates/actions/python-setup-poetry@v1.5.3
        with:
          poetry-version: "1.3.2"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint (flake8)
        run: poetry run pre-commit run flake8 --all-files --show-diff-on-failure

      - name: Order of imports (isort)
        run: poetry run pre-commit run isort --all-files --show-diff-on-failure

      - name: Formatting (black)
        run: poetry run pre-commit run black --all-files --show-diff-on-failure

      - name: Typing (mypy)
        run: poetry run pre-commit run mypy --all-files

      # TODO: enable when PEP 604 incompatibilty is in typer is resolved https://github.com/tiangolo/typer/issues/348
      # See https://github.com/tiangolo/typer/pull/522
      # - name: Syntax (pyupgrade)
      #   run: poetry run pre-commit run --hook-stage manual pyupgrade --all-files

      - name: Test
        run: poetry run pytest tests

      - name: Install docs dependencies
        run: poetry install --no-interaction --only docs

      - name: Generate docs
        run: sh ./gen_docs.sh
        shell: bash
  
  test-on-zsh:
    name: Test (zsh)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test pre-commit hooks in zsh
        uses: ./.github/actions/pre-commit-zsh

  publish:
    name: Publish
    needs: [test]
    uses: ./.github/workflows/publish-test-pypi.yaml
    secrets:
      test-pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}
