name: Testing changelog
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test changelog
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Create changelog
        id: build_changelog
        uses: bakdata/ci-templates/actions/changelog-generate@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          config: "./.github/changelog-config.json"
          new-tag: "1.1.4"
          old-tag: "1.0.0"
          fetchReviewers: "true"
          fetchReleaseInformation: "true"
      - name: Use output
        run: |
          echo "------------------------THIS IS TAG-----------------------------"
          echo  "${{ steps.build_changelog.outputs.single-changelog }}"
          echo "----------------------------------------------------------------"
          echo "------------------------THIS IS GLOBAL--------------------------"
          echo "${{ steps.build_changelog.outputs.merged-changelog }}"
          echo "----------------------------------------------------------------"
        shell: bash